import pytest, sys
import test_parser as parser

"""
Use global timeout everywhere because, due to the grouping, the parser does not
actually wait for the test outputs in the order in which they are produced. So,
the worst case might be that the first check_test() waits for the last line
produced by the test system.
"""
TEST_TIMEOUT = 30

OS_FileSystem_Type_FATFS = 1
OS_FileSystem_Type_SPIFFS = 2
OS_FileSystem_Type_LITTLEFS = 3

# AUTOGENERATED TEST FUNCTIONS BELOW -------------------------------------------

def test_OS_FileSystem_format(boot):
    """
    Format storage with all available FS libs, which is expected to work in case
    we have expectRemoval=0; if it is set to 1, we expect formatting to fail
    with a NOT_PRESENT error coming from the storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_format', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystem_mount(boot):
    """
    Mount storage with all available FS libs, which is expected to work in case
    we have expectRemoval=0; if it is set to 1, we expect mounting to fail
    with a NOT_PRESENT error coming from the storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystem_maxHandles(boot):
    """
    For all available FS libs, verify that the maximum number of file handles
    can be used at a time and check that a subsequent attempt to open a file
    results in an out-of-bounds error. Close all opened file handles afterwards.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_maxHandles', 'type=%i' % OS_FileSystem_Type_LITTLEFS, True, 2)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_maxHandles', 'type=%i' % OS_FileSystem_Type_SPIFFS, True, 2)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_maxHandles', 'type=%i' % OS_FileSystem_Type_FATFS, True, 2)

def test_OS_FileSystemFile_open(boot):
    """
    For each successful format and mount with one of the existing FS libs, open
    a file on the fs. This is expected to work when expectRemoval=0, and should
    fail with NOT_PRESENT error coming from the storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_open', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystemFile_write(boot):
    """
    For each successfully opened file perform several writes to it. This is
    expected to work when expectRemoval=0, and should fail with NOT_PRESENT
    error coming from the storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_write', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystemFile_read(boot):
    """
    For each successful writes to the opened file perform a read and check the
    results against what was written. This is expected to work when
    expectRemoval=0, and should fail with NOT_PRESENT error coming from the
    storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_read', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_read', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_read', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_read', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_read', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_read', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystemFile_close(boot):
    """
    For each successfully opened file close it again after writing/reading from
    it. This is expected to work when expectRemoval=0, and should fail with
    NOT_PRESENT error coming from the storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_close', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystemFile_getSize(boot):
    """
    For each successfully created file read its size and compare with the amount
    of bytes written. This is expected to work when expectRemoval=0, and should
    fail with NOT_PRESENT error coming from the storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_getSize', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_getSize', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_getSize', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_getSize', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_getSize', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_getSize', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystemFile_delete(boot):
    """
    For each successfully created file delete it again. This is expected to work
    when expectRemoval=0, and should fail with NOT_PRESENT error coming from the
    storage layer.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_delete', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_delete', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_delete', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_delete', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_delete', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystemFile_delete', 'expectRemoval=1,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystem_unmount(boot):
    """
    For each successfully mounted FS (once per each FS lib) unmount it again.
    This is always expected to work, as it should not touch the storage and thus
    won't learn that the medium was removed.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_unmount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_unmount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_LITTLEFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_unmount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_unmount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_SPIFFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_unmount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_unmount', 'expectRemoval=0,type=%i' % OS_FileSystem_Type_FATFS)

def test_OS_FileSystem_mount_fail(boot):
    """
    Format a FS with one FS type, then mount with a different one. Do this for
    all FS types. Calculate SHA256 on storage to make sure failed mounts do not
    change disk contents.
    """
    parser.check_test(boot(None), TEST_TIMEOUT, 'test_OS_FileSystem_mount_fail')
