#
# Copyright (C) 2019-2024, HENSOLDT Cyber GmbH
# 
# SPDX-License-Identifier: GPL-2.0-or-later
#
# For commercial licensing, contact: info.cyber@hensoldt.net
#

import pytest, sys
import test_parser as parser

TEST_NAME = 'test_entropysource'

# AUTOGENERATED TEST FUNCTIONS BELOW -------------------------------------------

def test_EntropySource_component(boot):
    """
    Get entropy from Crypto API through EntropySource component
    """
    parser.check_test(boot(TEST_NAME), 5, 'test_EntropySource_component')

def test_EntropySource_own(boot):
    """
    Get entropy from Crypto API through test-specific component
    """
    parser.check_test(boot(TEST_NAME), 3, 'test_EntropySource_own')
