import pytest, sys
import test_parser as parser

TEST_NAME = 'test_entropysource'

# AUTOGENERATED TEST FUNCTIONS BELOW -------------------------------------------

def test_EntropySource(boot):
    pass