import pytest, sys
import test_parser as parser

TEST_NAME = 'test_tlsserver'

# AUTOGENERATED TEST FUNCTIONS BELOW -------------------------------------------

def test_TlsServer_connect_neg_0(boot_with_proxy, tls_server):
    """
    Negative tests for TlsServer_connect(), covering the invalid ways of using this
    function thus verifying that it returns error codes instead of crashing
    """
    parser.check_test(boot_with_proxy(TEST_NAME), 5, 'test_TlsServer_connect_neg')


def test_TlsServer_connect_pos_0(boot_with_proxy, tls_server):
    """
    Positive tests for TlsServer_connect(), covering the valid ways of using this
    function.
    """
    parser.check_test(boot_with_proxy(TEST_NAME), 30, 'test_TlsServer_connect_pos')

def test_TlsServer_discconnect_pos_0(boot_with_proxy, tls_server):
    """
    Positive tests for TlsServer_disconnect(), covering the valid ways of using this
    function.
    """
    parser.check_test(boot_with_proxy(TEST_NAME), 3, 'test_TlsServer_disconnect_pos')

def test_TlsServer_disconnect_neg_0(boot_with_proxy, tls_server):
    """
    Negative tests for TlsServer_disconnect(), covering the invalid ways of using this
    function thus verifying that it returns error codes instead of crashing
    """
    parser.check_test(boot_with_proxy(TEST_NAME), 3, 'test_TlsServer_disconnect_neg')